"""add dimension value management

Revision ID: a1b2c3d4e5f6
Revises: 8ff90df7871d
Create Date: 2026-02-10 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '8ff90df7871d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 创建 dimension_value 表
    op.create_table(
        'dimension_value',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('oid', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('code', sa.Text(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('value_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('is_system', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('enabled', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('create_time', sa.DateTime(timezone=False), nullable=True),
        sa.Column('update_time', sa.DateTime(timezone=False), nullable=True),
        sa.Column('create_by', sa.BigInteger(), nullable=True),
        sa.Column('update_by', sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # 为 core_field 表添加 dimension_id 字段
    op.add_column('core_field', sa.Column('dimension_id', sa.BigInteger(), nullable=True))

    # 创建索引
    op.create_index('ix_dimension_value_oid_code', 'dimension_value', ['oid', 'code'], unique=True)
    op.create_index('ix_core_field_dimension_id', 'core_field', ['dimension_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 删除索引
    op.drop_index('ix_core_field_dimension_id', table_name='core_field')
    op.drop_index('ix_dimension_value_oid_code', table_name='dimension_value')

    # 删除 dimension_id 字段
    op.drop_column('core_field', 'dimension_id')

    # 删除 dimension_value 表
    op.drop_table('dimension_value')

    # ### end Alembic commands ###
